### ISSUE TITLE
Error when file has only comment

### ISSUE THREAD

**Issue by zoxon** [ThisIsManta/stylus-supremacy#27]
Test file
```styl
// comment
```

Output
```
» ./src/only-comment.styl
TypeError: Cannot read property 'map' of null
    at travel (E:\Work\stylsupermacy-test\node_modules\stylus-supremacy\edge\format.js:161:38)
    at format (E:\Work\stylsupermacy-test\node_modules\stylus-supremacy\edge\format.js:1296:21)
    at _.chain.reject.map.path (E:\Work\stylsupermacy-test\node_modules\stylus-supremacy\edge\commandLineProcessor.js:66:28)
    at arrayMap (E:\Work\stylsupermacy-test\node_modules\lodash\lodash.js:631:23)
    at Function.map (E:\Work\stylsupermacy-test\node_modules\lodash\lodash.js:9546:14)
    at interceptor (E:\Work\stylsupermacy-test\node_modules\lodash\lodash.js:16983:35)
    at thru (E:\Work\stylsupermacy-test\node_modules\lodash\lodash.js:8787:14)
    at E:\Work\stylsupermacy-test\node_modules\lodash\lodash.js:4380:28
    at arrayReduce (E:\Work\stylsupermacy-test\node_modules\lodash\lodash.js:675:21)
    at baseWrapperValue (E:\Work\stylsupermacy-test\node_modules\lodash\lodash.js:4379:14)
```

**Comment by ThisIsManta** [comment]
This issue has been fixed at [version 2.10.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.10.0)

Cheers!
